Trb 17
green-fox-academy/Rueppellii-Tribes-Backend1 pull request #19
Opened 2019-01-29 09:56 UTC by bleaksmile

2019-01-29 10:57 UTC, ChrisFrill commented on src/main/java/com/greenfox/tribes1/Building/BuildigService.java
> +public class BuildigService {
BuildigService --> please refactor to BuildingService

2019-01-29 11:00 UTC, ChrisFrill requested changes

2019-01-29 11:00 UTC, ChrisFrill commented on src/main/java/com/greenfox/tribes1/Building/BuildigService.java
> +public class BuildigService {
BuildigService --> please refactor to BuildingService

2019-01-29 11:21 UTC, ChrisFrill approved these changes

2019-01-29 12:22 UTC, lyancsie commented on src/main/java/com/greenfox/tribes1/Building/Barracks.java
> +}
The singular form is "Barrack"

2019-01-29 18:09 UTC, csadesz requested changes

2019-01-29 18:09 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/Building/BuildingService.java
> +  public Building saveBuilding(Building building){
Missing spaces after methods, and at the if statement.
Should look like:

if () {
}

2019-01-29 18:09 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/Building/BuildingType.java
> +public enum BuildingType {
Nice solution :)

2019-01-29 18:09 UTC, csadesz commented on src/test/java/com/greenfox/tribes1/Building/BuildingServiceTest.java
> +  Building barrack = new Barracks();
These could be private

2019-01-31 08:09 UTC, csadesz approved these changes

2019-01-31 08:11 UTC, merged