Trb 15
green-fox-academy/Rueppellii-Tribes-Backend1 pull request #20
Opened 2019-01-29 10:47 UTC by lyancsie

2019-01-29 11:08 UTC, bleaksmile requested changes

2019-01-29 11:08 UTC, bleaksmile commented on src/main/java/com/greenfox/tribes1/Kingdom/KingdomRepository.java
> +
empty line

2019-01-29 11:08 UTC, bleaksmile commented on src/main/java/com/greenfox/tribes1/Resources/KingdomResource.java
> +    amount = 500L;
please remove the amount

2019-01-29 11:08 UTC, bleaksmile commented on src/main/java/com/greenfox/tribes1/Resources/ResourceFactory.java
> +    if (ResourceFactory.isValid(resourceType)) {
code duplication

2019-01-29 11:08 UTC, bleaksmile commented on src/main/java/com/greenfox/tribes1/Resources/ResourceService.java
> +  public boolean validResource(KingdomResource resource) {
should this method check if it is null or not?

2019-01-29 11:48 UTC, bleaksmile approved these changes

2019-01-29 13:34 UTC, bleaksmile approved these changes

2019-01-31 11:19 UTC, bleaksmile approved these changes

2019-01-31 13:18 UTC, csadesz requested changes

2019-01-31 13:18 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/Resources/KingdomResource.java
> +  KingdomResource() {
you can use @NoArgsConstructor instead of that ( you've already used AllArgs)

2019-01-31 13:18 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/Kingdom/KingdomService.java
>    public boolean validKingdomName(String field) {
if the kingdom's name is null, it will crash

2019-02-04 14:42 UTC, csadesz approved these changes

2019-02-04 15:05 UTC, merged