Trb 38
green-fox-academy/Rueppellii-Tribes-Backend1 pull request #24
Opened 2019-01-29 13:26 UTC by lyancsie

Readme.md written with minimal formatting.

**Content:**

- Environment variables
- Common flyway errors with solutions
- Heroku (to be done by @bleaksmile)

2019-01-31 11:38 UTC, pitner33 approved these changes
Seems legit 👍

2019-01-31 13:20 UTC, csadesz requested changes

2019-01-31 13:20 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/Resources/Gold.java
> +@Data
Try not to use @Data, I know it contains everything what we need, but it's not to stable in some cases

2019-01-31 13:20 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/Resources/KingdomResource.java
> +    amount = 500L;
Than I see, why did you use default constructor 😄

2019-01-31 17:29 UTC, lyancsie commented on src/main/java/com/greenfox/tribes1/Resources/Gold.java
> +@Data
Okay, thanks, I won't use it

2019-02-04 12:31 UTC, csadesz approved these changes

2019-02-04 12:31 UTC, merged