Trb 8 - without /logout test
green-fox-academy/Rueppellii-Tribes-Backend1 pull request #28
Opened 2019-01-30 10:57 UTC by ChrisFrill

2019-01-31 08:31 UTC, bleaksmile requested changes

2019-01-31 08:31 UTC, bleaksmile commented on src/main/java/com/greenfox/tribes1/ApplicationUser/DTO/ApplicationUserDTO.java
empty line

2019-01-31 08:35 UTC, bleaksmile approved these changes

2019-01-31 13:22 UTC, csadesz requested changes

2019-01-31 13:22 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/ApplicationUser/ApplicationUser.java
> +@Data
Is it still there?

2019-01-31 13:22 UTC, csadesz commented on src/main/java/com/greenfox/tribes1/ApplicationUser/DTO/ApplicationUserDTO.java
> +@AllArgsConstructor
Maybe you didn't push your changes, that's why it isnt in a queue

2019-02-01 14:48 UTC, csadesz approved these changes

2019-02-01 17:02 UTC, merged