(add) add tests to the new KindomService methods
green-fox-academy/Rueppellii-Tribes-Backend1 pull request #29
Opened 2019-01-31 09:40 UTC by pitner33

2019-01-31 09:41 UTC, pitner33 commented
TRB-18 valahol lemaradt

2019-01-31 13:23 UTC, bleaksmile approved these changes

2019-01-31 13:25 UTC, csadesz approved these changes

2019-01-31 13:25 UTC, csadesz commented on src/test/java/com/greenfox/tribes1/Kingdom/KingdomServiceTest.java
> +  private Kingdom validKingdom2 = new Kingdom("Rueppellii");
It is not a good practice to use variable names like this. Maybe you can refactor these names to validKingdomRueppellii, validKingdomNarnia

2019-01-31 13:26 UTC, csadesz requested changes
variable's name

2019-01-31 13:58 UTC, pitner33 commented
variable names refactored

2019-02-01 08:48 UTC, csadesz approved these changes

2019-02-01 12:09 UTC, merged